### ISSUE TITLE
Chart Goes Somewhere

### ISSUE THREAD

**Issue by alexanderrudnik** [altence/lightence-admin#155]
**To Reproduce**

**Screenshots**
https://i.imgur.com/V3VZI3F.png

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by uclnj** [comment]
Sporadic issues are the worst to track down but I was able to get it to happen each time by having the viewport around 1200px wide then as the graphs begin to draw, maximize the window to a full 5120 and the graphs freeze in [mid-draw](https://i.imgur.com/C9cLrwm.png).

**Comment by alexanderrudnik** [comment]
@leineveber please check if your PR fixed this

**Comment by leineveber** [comment]
> Sporadic issues are the worst to track down but I was able to get it to happen each time by having the viewport around 1200px wide then as the graphs begin to draw, maximize the window to a full 5120 and the graphs freeze in [mid-draw](https://i.imgur.com/C9cLrwm.png).

thanks for your help!
fixed
