### ISSUE TITLE
Bell & Settings Icons in Header

### ISSUE THREAD

**Issue by alexanderrudnik** [altence/lightence-admin#166]
Add visual effects while hovering

**Comment by leineveber** [comment]
added in pr #186

**Comment by alexanderrudnik** [comment]
New visual effects are hardly noticeable, especially on the dark theme. You can try to update icon color while hovering. And do not change icons positions:
![image](https://user-images.githubusercontent.com/9514327/152040552-c56f4b5c-6c5f-41a1-be6f-25a544501091.png)

**Comment by leineveber** [comment]
fixed
