### ISSUE TITLE
Login: Wrong Font

### ISSUE THREAD

**Issue by alexanderrudnik** [altence/lightence-admin#180]
**Describe the bug**
`email` and `password` inputs use different fonts
The same issue for Sign up form as well

**Expected behavior**
`email` and `password` should both use Montserrat font.

**Comment by RishiKumarRay** [comment]
wher can i find the code?

**Comment by alexanderrudnik** [comment]
@RishiKumarRay 
please try `src/components/auth/LoginForm/LoginForm.styles.ts`

**Comment by RishiKumarRay** [comment]
I was not able to locate the code which decides the fonts?

**Comment by leineveber** [comment]
its not true, they use the same font family but different font weight and font size

**Comment by leineveber** [comment]
fixed in #190
