### ISSUE TITLE
Step Form: Missing i18n

### ISSUE THREAD

**Issue by alexanderrudnik** [altence/lightence-admin#182]
**Describe the bug**
There are missing i18n for error messages in Step Form

**Expected behavior**
Add i18n and check all messages on having the corresponding i18n.

**Screenshots**
![image](https://user-images.githubusercontent.com/9514327/151953082-c8678193-4224-4f57-89ff-b98ce0452dbd.png)

**Comment by leineveber** [comment]
fixed in #189
