### ISSUE TITLE
Step Form ForwardRef Error

### ISSUE THREAD

**Issue by alexanderrudnik** [altence/lightence-admin#193]
**Describe the bug**
`ForwardRef` error

**To Reproduce**
1. Go to Advanced Forms -> Step Form
2. Click `Next` button
3. You will see an error in the console

**Expected behavior**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/9514327/152038984-712f7a05-9480-4939-93b5-243f4e113d57.png)

**Comment by leineveber** [comment]
fixed in pr #196
