### ISSUE TITLE
Kanban Extra Settings Missing Hover Effect

### ISSUE THREAD

**Issue by alexanderrudnik** [altence/lightence-admin#194]
**Describe the bug**
No hover effect on Kanban Card Extra settings dropdown

**To Reproduce**
1. Go to Kanban
2. Click on '...'
3. You will see that there is missing hover effect

**Expected behavior**
Add hover effect

**Screenshots**
![image](https://user-images.githubusercontent.com/9514327/152041030-91e242f2-48c8-47a2-a60c-69f87978b538.png)

**Comment by leineveber** [comment]
added in pr #197
