### ISSUE TITLE
Could not build / start the project

### ISSUE THREAD

**Issue by weird-oecophylla** [altence/lightence-admin#286]
Using yarn install and then yarn start as mentioned in readme does not work.

- The yarn install command worked fine.
- The yarn start command failed.

I obtain the following error:

```
{
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v21.6.0
```

**To Reproduce**
1. git clone 
2. yarn install && yarn start

**Expected behavior**
Successfull yarn start

**Comment by dogmatic69** [comment]
https://github.com/altence/lightence-ant-design-react-template/blob/main/package.json#L122-L124

add this option to your node environment and it will on v21.
```
--openssl-legacy-provider 
``

**Comment by sanjib-suna** [comment]
Getting same issue, @weird-oecophylla have you find any resolution on this?

**Comment by jin-li** [comment]
I got the same error after upgrading my Node.js to v20.11.0. The error is caused by Node.js v17 fixing a security hole in the SSL provider, see [https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported). Most answers in this post suggest to downgrade Node.js to v16. But obviously it's not a good idea.

After several tries, this works for me (I am using Ubuntu 22):
```bash
export NODE_OPTIONS==--openssl-legacy-provider
yarn install
yarn start
```

**Comment by weird-oecophylla** [comment]
Adding $env:NODE_OPTIONS = "--openssl-legacy-provider" (Powershell)
 worked for me.

However it ends now with the following error:

`  
src\utils\utils.ts
  Line 1:93:    Delete `␍`  prettier/prettier
  Line 2:61:    Delete `␍`  prettier/prettier
  Line 3:61:    Delete `␍`  prettier/prettier
  Line 4:73:    Delete `␍`  prettier/prettier
  Line 5:67:    Delete `␍`  prettier/prettier
  Line 6:73:    Delete `␍`  prettier/prettier
  Line 7:77:    Delete `␍`  prettier/prettier
  Line 8:63:    Delete `␍`  prettier/prettier
  Line 9:1:     Delete `␍`  prettier/prettier
  Line 10:54:   Delete `␍`  prettier/prettier
  Line 11:16:   Delete `␍`  prettier/prettier
  Line 12:16:   Delete `␍`  prettier/prettier
  Line 13:102:  Delete `␍`  prettier/prettier
  Line 14:15:   Delete `␍`  prettier/prettier
  Line 15:3:    Delete `␍`  prettier/prettier
  Line 16:1:    Delete `␍`  prettier/prettier
  Line 17:113:  Delete `␍`  prettier/prettier
  Line 18:73:   Delete `␍`  prettier/prettier
  Line 19:1:    Delete `␍`  prettier/prettier
  Line 20:78:   Delete `␍`  prettier/prettier
  Line 21:3:    Delete `␍`  prettier/prettier
  Line 22:1:    Delete `␍`  prettier/prettier
  Line 23:18:   Delete `␍`  prettier/prettier
  Line 24:17:   Delete `␍`  prettier/prettier
  Line 25:3:    Delete `␍`  prettier/prettier
  Line 26:1:    Delete `␍`  prettier/prettier
  Line 27:76:   Delete `␍`  prettier/prettier
  Line 28:28:   Delete `␍`  prettier/prettier
  Line 29:6:    Delete `␍`  prettier/prettier
  Line 30:24:   Delete `␍`  prettier/prettier
  Line 31:7:    Delete `␍`  prettier/prettier
  Line 32:6:    Delete `␍`  prettier/prettier
  Line 33:28:   Delete `␍`  prettier/prettier
  Line 34:7:    Delete `␍`  prettier/prettier
  Line 35:6:    Delete `␍`  prettier/prettier
  Line 36:1:    Delete `␍`  prettier/prettier
  Line 37:96:   Delete `␍`  prettier/prettier
  Line 38:1:    Delete `␍`  prettier/prettier
  Line 39:51:   Delete `␍`  prettier/prettier
  Line 40:43:   Delete `␍`  prettier/prettier
  Line 41:39:   Delete `␍`  prettier/prettier
  Line 42:39:   Delete `␍`  prettier/prettier
  Line 43:1:    Delete `␍`  prettier/prettier
  Line 44:29:   Delete `␍`  prettier/prettier
  Line 45:3:    Delete `␍`  prettier/prettier
  Line 46:1:    Delete `␍`  prettier/prettier
  Line 47:82:   Delete `␍`  prettier/prettier
  Line 48:97:   Delete `␍`  prettier/prettier
  Line 49:1:    Delete `␍`  prettier/prettier
  Line 50:83:   Delete `␍`  prettier/prettier
  Line 51:116:  Delete `␍`  prettier/prettier
  Line 52:1:    Delete `␍`  prettier/prettier
  Line 53:71:   Delete `␍`  prettier/prettier
  Line 54:22:   Delete `␍`  prettier/prettier
  Line 55:24:   Delete `␍`  prettier/prettier
  Line 56:37:   Delete `␍`  prettier/prettier
  Line 57:23:   Delete `␍`  prettier/prettier
  Line 58:37:   Delete `␍`  prettier/prettier
  Line 59:26:   Delete `␍`  prettier/prettier
  Line 60:37:   Delete `␍`  prettier/prettier
  Line 61:24:   Delete `␍`  prettier/prettier
  Line 62:35:   Delete `␍`  prettier/prettier
  Line 63:13:   Delete `␍`  prettier/prettier
  Line 64:37:   Delete `␍`  prettier/prettier
  Line 65:4:    Delete `␍`  prettier/prettier
  Line 66:3:    Delete `␍`  prettier/prettier
  Line 67:1:    Delete `␍`  prettier/prettier
  Line 68:104:  Delete `␍`  prettier/prettier
  Line 69:47:   Delete `␍`  prettier/prettier
  Line 70:22:   Delete `␍`  prettier/prettier
  Line 71:18:   Delete `␍`  prettier/prettier
  Line 72:20:   Delete `␍`  prettier/prettier
  Line 73:20:   Delete `␍`  prettier/prettier
  Line 74:46:   Delete `␍`  prettier/prettier
  Line 75:17:   Delete `␍`  prettier/prettier
  Line 76:13:   Delete `␍`  prettier/prettier
  Line 77:42:   Delete `␍`  prettier/prettier
  Line 78:4:    Delete `␍`  prettier/prettier
  Line 79:3:    Delete `␍`  prettier/prettier
  Line 80:1:    Delete `␍`  prettier/prettier
  Line 81:63:   Delete `␍`  prettier/prettier
  Line 82:67:   Delete `␍`  prettier/prettier
  Line 83:82:   Delete `␍`  prettier/prettier
  Line 84:1:    Delete `␍`  prettier/prettier
  Line 85:76:   Delete `␍`  prettier/prettier
  Line 86:39:   Delete `␍`  prettier/prettier
  Line 87:49:   Delete `␍`  prettier/prettier
  Line 88:49:   Delete `␍`  prettier/prettier
  Line 89:1:    Delete `␍`  prettier/prettier
  Line 90:44:   Delete `␍`  prettier/prettier
  Line 91:3:    Delete `␍`  prettier/prettier
  Line 92:1:    Delete `␍`  prettier/prettier
  Line 93:72:   Delete `␍`  prettier/prettier
  Line 94:47:   Delete `␍`  prettier/prettier
  Line 95:47:   Delete `␍`  prettier/prettier
  Line 96:47:   Delete `␍`  prettier/prettier
  Line 97:1:    Delete `␍`  prettier/prettier
  Line 98:58:   Delete `␍`  prettier/prettier
  Line 99:58:   Delete `␍`  prettier/prettier
  Line 100:58:  Delete `␍`  prettier/prettier
  Line 101:1:   Delete `␍`  prettier/prettier
  Line 102:25:  Delete `␍`  prettier/prettier
  Line 103:25:  Delete `␍`  prettier/prettier
  Line 104:25:  Delete `␍`  prettier/prettier
  Line 105:1:   Delete `␍`  prettier/prettier
  Line 106:81:  Delete `␍`  prettier/prettier
  Line 107:81:  Delete `␍`  prettier/prettier
  Line 108:81:  Delete `␍`  prettier/prettier
  Line 109:1:   Delete `␍`  prettier/prettier
  Line 110:29:  Delete `␍`  prettier/prettier
  Line 111:3:   Delete `␍`  prettier/prettier
  Line 112:1:   Delete `␍`  prettier/prettier
  Line 113:80:  Delete `␍`  prettier/prettier
  Line 114:72:  Delete `␍`  prettier/prettier
  Line 115:1:   Delete `␍`  prettier/prettier
  Line 116:16:  Delete `␍`  prettier/prettier
  Line 117:37:  Delete `␍`  prettier/prettier
  Line 118:37:  Delete `␍`  prettier/prettier
  Line 119:37:  Delete `␍`  prettier/prettier
  Line 120:40:  Delete `␍`  prettier/prettier
  Line 121:35:  Delete `␍`  prettier/prettier
  Line 122:31:  Delete `␍`  prettier/prettier
  Line 123:14:  Delete `␍`  prettier/prettier
  Line 124:31:  Delete `␍`  prettier/prettier
  Line 125:22:  Delete `␍`  prettier/prettier
  Line 126:31:  Delete `␍`  prettier/prettier
  Line 127:13:  Delete `␍`  prettier/prettier
  Line 128:27:  Delete `␍`  prettier/prettier
  Line 129:59:  Delete `␍`  prettier/prettier
  Line 130:21:  Delete `␍`  prettier/prettier
  Line 131:16:  Delete `␍`  prettier/prettier
  Line 132:45:  Delete `␍`  prettier/prettier
  Line 133:17:  Delete `␍`  prettier/prettier
  Line 134:16:  Delete `␍`  prettier/prettier
  Line 135:31:  Delete `␍`  prettier/prettier
  Line 136:17:  Delete `␍`  prettier/prettier
  Line 137:16:  Delete `␍`  prettier/prettier
  Line 138:31:  Delete `␍`  prettier/prettier
  Line 139:17:  Delete `␍`  prettier/prettier
  Line 140:17:  Delete `␍`  prettier/prettier
  Line 141:17:  Delete `␍`  prettier/prettier
  Line 142:8:   Delete `␍`  prettier/prettier
  Line 143:14:  Delete `␍`  prettier/prettier
  Line 144:6:   Delete `␍`  prettier/prettier
  Line 145:13:  Delete `␍`  prettier/prettier
  Line 146:9:   Delete `␍`  prettier/prettier
  Line 147:9:   Delete `␍`  prettier/prettier
  Line 148:9:   Delete `␍`  prettier/prettier
  Line 149:7:   Delete `␍`  prettier/prettier
  Line 150:11:  Delete `␍`  prettier/prettier
  Line 151:44:  Delete `␍`  prettier/prettier
  Line 152:4:   Delete `␍`  prettier/prettier
  Line 153:3:   Delete `␍`  prettier/prettier
  Line 154:1:   Delete `␍`  prettier/prettier
  Line 155:67:  Delete `␍`  prettier/prettier
  Line 156:65:  Delete `␍`  prettier/prettier
  Line 157:3:   Delete `␍`  prettier/prettier
  Line 158:71:  Delete `␍`  prettier/prettier
  Line 159:1:   Delete `␍`  prettier/prettier
  Line 160:57:  Delete `␍`  prettier/prettier
  Line 161:1:   Delete `␍`  prettier/prettier
  Line 162:73:  Delete `␍`  prettier/prettier
  Line 163:18:  Delete `␍`  prettier/prettier
  Line 164:17:  Delete `␍`  prettier/prettier
  Line 165:19:  Delete `␍`  prettier/prettier
  Line 166:23:  Delete `␍`  prettier/prettier
  Line 167:25:  Delete `␍`  prettier/prettier
  Line 168:20:  Delete `␍`  prettier/prettier
  Line 169:22:  Delete `␍`  prettier/prettier
  Line 170:17:  Delete `␍`  prettier/prettier
  Line 171:21:  Delete `␍`  prettier/prettier
  Line 172:21:  Delete `␍`  prettier/prettier
  Line 173:25:  Delete `␍`  prettier/prettier
  Line 174:19:  Delete `␍`  prettier/prettier
  Line 175:23:  Delete `␍`  prettier/prettier
  Line 176:16:  Delete `␍`  prettier/prettier
  Line 177:20:  Delete `␍`  prettier/prettier
  Line 178:21:  Delete `␍`  prettier/prettier
  Line 179:25:  Delete `␍`  prettier/prettier
  Line 180:13:  Delete `␍`  prettier/prettier
  Line 181:19:  Delete `␍`  prettier/prettier
  Line 182:4:   Delete `␍`  prettier/prettier
  Line 183:3:   Delete `␍`  prettier/prettier
  Line 184:1:   Delete `␍`  prettier/prettier
  Line 185:80:  Delete `␍`  prettier/prettier
  Line 186:68:  Delete `␍`  prettier/prettier
  Line 187:19:  Delete `␍`  prettier/prettier
  Line 188:4:   Delete `␍`  prettier/prettier
  Line 189:1:   Delete `␍`  prettier/prettier
  Line 190:17:  Delete `␍`  prettier/prettier
  Line 191:3:   Delete `␍`  prettier/prettier

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

`

**Comment by weird-oecophylla** [comment]
The following configuration worked for bypassing ssl errors.

![image](https://github.com/altence/lightence-ant-design-react-template/assets/38054816/0aa941d8-72f3-4225-bf0a-31db5b538893)

Problem solved !
